### PR TITLE
Added try catch for handling empty response

### PR DESCRIPTION
**Pull request by ikrish99**
We had a issue with the usabilla api, where the rest call response was empty and the function handleonEnd was trying to convert the empty response to JSON and it failed. As its a callback function for me. I can't handle the error in the library.

Please review it and approve the PR.

Thanks

### CODE REVIEW

**Comment by spirosikmd** [comment]
Hi @ikrish99! Thank you for your contribution. There is a new version available [`v1.2.2`](https://github.com/usabilla/api-js-node/releases/tag/v1.2.2). Can you give it a try? Please update this PR if it still not working for you.

**Comment by ikrish99** [comment]
Hello spirosikmd. I think the code I have is not compatible for using v1.2.2. I see lot of changes in new version. If you can the accept the pull request I will set old version in package.json and slowly move to latest version

Thanks.

**Comment by spirosikmd** [comment]
Hi @ikrish99! You shouldn't need to make any changes to the code that is using this library. The changes in v1.2.2 are only internal refactoring changes. The public interface of the library is still the same. 

Have you tried version v1.2.2 and is the issue still happening? If the issue is not happening anymore, then we can close this PR. Otherwise, we can update this PR to handle the issue differently.

**Comment by renatomefi** [comment]
I think we can close this one :)

**Pull request closed without merging**
