### PR TITLE
fix(resource): use initial params for subsequent iteration requests

### LINKED ISSUE #29: Why iterator isn't a param configurable?
I don't understand the iterator parameter in the index.js file. There are no references in the documentation.
However, this parameter causes my API searches lose their search parameters after the first iteration. Especially when I want to request the last 10 (or n) feedbacks. Only the first iteration sends the correct parameters, then the default parameters are sent and not those that I sent.

```
src/index.js : constructor()

this.config = {
  method: 'GET',
  host: 'data.usabilla.com',
  iterator: true // THIS ... ¿WHY?
};
```

### PR DESCRIPTION
**Pull request by spirosikmd**
Closes #29

### CODE REVIEW

**Comment by ivolivares** [comment]
@shuisman why not publish this version on npm? I really need to continue my development ASAP with your API. What is the procedure? If you close the #29 issue, why not publish the solution?
Thanks!

**Comment by spirosikmd** [comment]
Hi @ivolivares! We will publish a new version. Please be patient! This is an open source project 😄 We are also setting up [semantic-release](https://github.com/semantic-release/semantic-release) so new versions will be published automatically in the future. You are more than welcome to submit PRs for issues that are urgent to you. Thanks a lot!

**Comment by ivolivares** [comment]
@spirosikmd We really need this fix urgently, without this we can't use your API. ¿Any option to get a patch version? Thanks!

**Comment by spirosikmd** [comment]
Hi @ivolivares! A [new version](https://github.com/usabilla/api-js-node/releases/tag/v1.0.5) has already been released with the patch fix 🎉 As you depend on this project a lot, maybe you should watch it, to get notified of new versions?

**Comment by ivolivares** [comment]
@spirosikmd Really really thanks ! :smile:

**Pull request merged**
